// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: delivery.proto

package deliverypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_AssignDelivery_FullMethodName            = "/delivery.v1.DeliveryService/AssignDelivery"
	DeliveryService_GetDeliveryById_FullMethodName           = "/delivery.v1.DeliveryService/GetDeliveryById"
	DeliveryService_UpdateDeliveryStatus_FullMethodName      = "/delivery.v1.DeliveryService/UpdateDeliveryStatus"
	DeliveryService_GetDeliveriesByCourier_FullMethodName    = "/delivery.v1.DeliveryService/GetDeliveriesByCourier"
	DeliveryService_GetDeliveriesByOrder_FullMethodName      = "/delivery.v1.DeliveryService/GetDeliveriesByOrder"
	DeliveryService_ListAvailableCouriers_FullMethodName     = "/delivery.v1.DeliveryService/ListAvailableCouriers"
	DeliveryService_GetDeliveryStats_FullMethodName          = "/delivery.v1.DeliveryService/GetDeliveryStats"
	DeliveryService_CalculateDeliveryETA_FullMethodName      = "/delivery.v1.DeliveryService/CalculateDeliveryETA"
	DeliveryService_GetDeliveryHistory_FullMethodName        = "/delivery.v1.DeliveryService/GetDeliveryHistory"
	DeliveryService_RateCourier_FullMethodName               = "/delivery.v1.DeliveryService/RateCourier"
	DeliveryService_RegisterCourier_FullMethodName           = "/delivery.v1.DeliveryService/RegisterCourier"
	DeliveryService_UpdateCourierAvailability_FullMethodName = "/delivery.v1.DeliveryService/UpdateCourierAvailability"
	DeliveryService_HealthCheck_FullMethodName               = "/delivery.v1.DeliveryService/HealthCheck"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	AssignDelivery(ctx context.Context, in *AssignDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	GetDeliveryById(ctx context.Context, in *GetDeliveryByIdRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	GetDeliveriesByCourier(ctx context.Context, in *GetDeliveriesByCourierRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error)
	GetDeliveriesByOrder(ctx context.Context, in *GetDeliveriesByOrderRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error)
	ListAvailableCouriers(ctx context.Context, in *ListAvailableCouriersRequest, opts ...grpc.CallOption) (*ListCouriersResponse, error)
	GetDeliveryStats(ctx context.Context, in *GetDeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error)
	CalculateDeliveryETA(ctx context.Context, in *CalculateDeliveryETARequest, opts ...grpc.CallOption) (*DeliveryETAResponse, error)
	GetDeliveryHistory(ctx context.Context, in *GetDeliveryHistoryRequest, opts ...grpc.CallOption) (*DeliveryHistoryResponse, error)
	RateCourier(ctx context.Context, in *RateCourierRequest, opts ...grpc.CallOption) (*CourierRatingResponse, error)
	RegisterCourier(ctx context.Context, in *RegisterCourierRequest, opts ...grpc.CallOption) (*CourierResponse, error)
	UpdateCourierAvailability(ctx context.Context, in *UpdateCourierAvailabilityRequest, opts ...grpc.CallOption) (*CourierResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) AssignDelivery(ctx context.Context, in *AssignDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, DeliveryService_AssignDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryById(ctx context.Context, in *GetDeliveryByIdRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveriesByCourier(ctx context.Context, in *GetDeliveriesByCourierRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveriesResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveriesByCourier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveriesByOrder(ctx context.Context, in *GetDeliveriesByOrderRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveriesResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveriesByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ListAvailableCouriers(ctx context.Context, in *ListAvailableCouriersRequest, opts ...grpc.CallOption) (*ListCouriersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouriersResponse)
	err := c.cc.Invoke(ctx, DeliveryService_ListAvailableCouriers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryStats(ctx context.Context, in *GetDeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryStatsResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CalculateDeliveryETA(ctx context.Context, in *CalculateDeliveryETARequest, opts ...grpc.CallOption) (*DeliveryETAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryETAResponse)
	err := c.cc.Invoke(ctx, DeliveryService_CalculateDeliveryETA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryHistory(ctx context.Context, in *GetDeliveryHistoryRequest, opts ...grpc.CallOption) (*DeliveryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryHistoryResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) RateCourier(ctx context.Context, in *RateCourierRequest, opts ...grpc.CallOption) (*CourierRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourierRatingResponse)
	err := c.cc.Invoke(ctx, DeliveryService_RateCourier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) RegisterCourier(ctx context.Context, in *RegisterCourierRequest, opts ...grpc.CallOption) (*CourierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourierResponse)
	err := c.cc.Invoke(ctx, DeliveryService_RegisterCourier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateCourierAvailability(ctx context.Context, in *UpdateCourierAvailabilityRequest, opts ...grpc.CallOption) (*CourierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourierResponse)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateCourierAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DeliveryService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	AssignDelivery(context.Context, *AssignDeliveryRequest) (*DeliveryResponse, error)
	GetDeliveryById(context.Context, *GetDeliveryByIdRequest) (*DeliveryResponse, error)
	UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*DeliveryResponse, error)
	GetDeliveriesByCourier(context.Context, *GetDeliveriesByCourierRequest) (*ListDeliveriesResponse, error)
	GetDeliveriesByOrder(context.Context, *GetDeliveriesByOrderRequest) (*ListDeliveriesResponse, error)
	ListAvailableCouriers(context.Context, *ListAvailableCouriersRequest) (*ListCouriersResponse, error)
	GetDeliveryStats(context.Context, *GetDeliveryStatsRequest) (*DeliveryStatsResponse, error)
	CalculateDeliveryETA(context.Context, *CalculateDeliveryETARequest) (*DeliveryETAResponse, error)
	GetDeliveryHistory(context.Context, *GetDeliveryHistoryRequest) (*DeliveryHistoryResponse, error)
	RateCourier(context.Context, *RateCourierRequest) (*CourierRatingResponse, error)
	RegisterCourier(context.Context, *RegisterCourierRequest) (*CourierResponse, error)
	UpdateCourierAvailability(context.Context, *UpdateCourierAvailabilityRequest) (*CourierResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) AssignDelivery(context.Context, *AssignDeliveryRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryById(context.Context, *GetDeliveryByIdRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryById not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveriesByCourier(context.Context, *GetDeliveriesByCourierRequest) (*ListDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveriesByCourier not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveriesByOrder(context.Context, *GetDeliveriesByOrderRequest) (*ListDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveriesByOrder not implemented")
}
func (UnimplementedDeliveryServiceServer) ListAvailableCouriers(context.Context, *ListAvailableCouriersRequest) (*ListCouriersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableCouriers not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryStats(context.Context, *GetDeliveryStatsRequest) (*DeliveryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryStats not implemented")
}
func (UnimplementedDeliveryServiceServer) CalculateDeliveryETA(context.Context, *CalculateDeliveryETARequest) (*DeliveryETAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateDeliveryETA not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryHistory(context.Context, *GetDeliveryHistoryRequest) (*DeliveryHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryHistory not implemented")
}
func (UnimplementedDeliveryServiceServer) RateCourier(context.Context, *RateCourierRequest) (*CourierRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateCourier not implemented")
}
func (UnimplementedDeliveryServiceServer) RegisterCourier(context.Context, *RegisterCourierRequest) (*CourierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCourier not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateCourierAvailability(context.Context, *UpdateCourierAvailabilityRequest) (*CourierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCourierAvailability not implemented")
}
func (UnimplementedDeliveryServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_AssignDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).AssignDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_AssignDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).AssignDelivery(ctx, req.(*AssignDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryById(ctx, req.(*GetDeliveryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, req.(*UpdateDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveriesByCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveriesByCourierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveriesByCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveriesByCourier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveriesByCourier(ctx, req.(*GetDeliveriesByCourierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveriesByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveriesByOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveriesByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveriesByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveriesByOrder(ctx, req.(*GetDeliveriesByOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ListAvailableCouriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableCouriersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ListAvailableCouriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ListAvailableCouriers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ListAvailableCouriers(ctx, req.(*ListAvailableCouriersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryStats(ctx, req.(*GetDeliveryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CalculateDeliveryETA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDeliveryETARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CalculateDeliveryETA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CalculateDeliveryETA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CalculateDeliveryETA(ctx, req.(*CalculateDeliveryETARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryHistory(ctx, req.(*GetDeliveryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_RateCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateCourierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).RateCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_RateCourier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).RateCourier(ctx, req.(*RateCourierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_RegisterCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCourierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).RegisterCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_RegisterCourier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).RegisterCourier(ctx, req.(*RegisterCourierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateCourierAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCourierAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateCourierAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateCourierAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateCourierAvailability(ctx, req.(*UpdateCourierAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.v1.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignDelivery",
			Handler:    _DeliveryService_AssignDelivery_Handler,
		},
		{
			MethodName: "GetDeliveryById",
			Handler:    _DeliveryService_GetDeliveryById_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _DeliveryService_UpdateDeliveryStatus_Handler,
		},
		{
			MethodName: "GetDeliveriesByCourier",
			Handler:    _DeliveryService_GetDeliveriesByCourier_Handler,
		},
		{
			MethodName: "GetDeliveriesByOrder",
			Handler:    _DeliveryService_GetDeliveriesByOrder_Handler,
		},
		{
			MethodName: "ListAvailableCouriers",
			Handler:    _DeliveryService_ListAvailableCouriers_Handler,
		},
		{
			MethodName: "GetDeliveryStats",
			Handler:    _DeliveryService_GetDeliveryStats_Handler,
		},
		{
			MethodName: "CalculateDeliveryETA",
			Handler:    _DeliveryService_CalculateDeliveryETA_Handler,
		},
		{
			MethodName: "GetDeliveryHistory",
			Handler:    _DeliveryService_GetDeliveryHistory_Handler,
		},
		{
			MethodName: "RateCourier",
			Handler:    _DeliveryService_RateCourier_Handler,
		},
		{
			MethodName: "RegisterCourier",
			Handler:    _DeliveryService_RegisterCourier_Handler,
		},
		{
			MethodName: "UpdateCourierAvailability",
			Handler:    _DeliveryService_UpdateCourierAvailability_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DeliveryService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery.proto",
}
