// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: delivery.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageMeta) Reset() {
	*x = PageMeta{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageMeta) ProtoMessage() {}

func (x *PageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageMeta.ProtoReflect.Descriptor instead.
func (*PageMeta) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *PageMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageMeta) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageMeta) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Courier struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName        string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleType     string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Rating          float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalDeliveries int32                  `protobuf:"varint,7,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	IsAvailable     bool                   `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Courier) Reset() {
	*x = Courier{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Courier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courier) ProtoMessage() {}

func (x *Courier) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courier.ProtoReflect.Descriptor instead.
func (*Courier) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *Courier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Courier) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Courier) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Courier) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Courier) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *Courier) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Courier) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *Courier) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Courier) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Courier) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Delivery struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId             string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CourierId           string                 `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	RestaurantId        string                 `protobuf:"bytes,4,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PickupAddress       string                 `protobuf:"bytes,7,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,8,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	EstimatedEtaMinutes int32                  `protobuf:"varint,9,opt,name=estimated_eta_minutes,json=estimatedEtaMinutes,proto3" json:"estimated_eta_minutes,omitempty"`
	PickupTime          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	DeliveredTime       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=delivered_time,json=deliveredTime,proto3" json:"delivered_time,omitempty"`
	RouteDistanceKm     float64                `protobuf:"fixed64,12,opt,name=route_distance_km,json=routeDistanceKm,proto3" json:"route_distance_km,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Delivery) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *Delivery) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *Delivery) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Delivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Delivery) GetPickupAddress() string {
	if x != nil {
		return x.PickupAddress
	}
	return ""
}

func (x *Delivery) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Delivery) GetEstimatedEtaMinutes() int32 {
	if x != nil {
		return x.EstimatedEtaMinutes
	}
	return 0
}

func (x *Delivery) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *Delivery) GetDeliveredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredTime
	}
	return nil
}

func (x *Delivery) GetRouteDistanceKm() float64 {
	if x != nil {
		return x.RouteDistanceKm
	}
	return 0
}

func (x *Delivery) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delivery) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeliveryStatusHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	OldStatus     string                 `protobuf:"bytes,3,opt,name=old_status,json=oldStatus,proto3" json:"old_status,omitempty"`
	NewStatus     string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatusHistory) Reset() {
	*x = DeliveryStatusHistory{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatusHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatusHistory) ProtoMessage() {}

func (x *DeliveryStatusHistory) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatusHistory.ProtoReflect.Descriptor instead.
func (*DeliveryStatusHistory) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryStatusHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryStatusHistory) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryStatusHistory) GetOldStatus() string {
	if x != nil {
		return x.OldStatus
	}
	return ""
}

func (x *DeliveryStatusHistory) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *DeliveryStatusHistory) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

type CourierRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourierId     string                 `protobuf:"bytes,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierRating) Reset() {
	*x = CourierRating{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRating) ProtoMessage() {}

func (x *CourierRating) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRating.ProtoReflect.Descriptor instead.
func (*CourierRating) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *CourierRating) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourierRating) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *CourierRating) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CourierRating) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CourierRating) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CourierRating) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CourierRating) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeliveryStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalDeliveries     int64                  `protobuf:"varint,1,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	ActiveDeliveries    int64                  `protobuf:"varint,2,opt,name=active_deliveries,json=activeDeliveries,proto3" json:"active_deliveries,omitempty"`
	CompletedDeliveries int64                  `protobuf:"varint,3,opt,name=completed_deliveries,json=completedDeliveries,proto3" json:"completed_deliveries,omitempty"`
	CancelledDeliveries int64                  `protobuf:"varint,4,opt,name=cancelled_deliveries,json=cancelledDeliveries,proto3" json:"cancelled_deliveries,omitempty"`
	AverageEtaMinutes   float64                `protobuf:"fixed64,5,opt,name=average_eta_minutes,json=averageEtaMinutes,proto3" json:"average_eta_minutes,omitempty"`
	AverageDistanceKm   float64                `protobuf:"fixed64,6,opt,name=average_distance_km,json=averageDistanceKm,proto3" json:"average_distance_km,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeliveryStats) Reset() {
	*x = DeliveryStats{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStats) ProtoMessage() {}

func (x *DeliveryStats) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStats.ProtoReflect.Descriptor instead.
func (*DeliveryStats) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryStats) GetTotalDeliveries() int64 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *DeliveryStats) GetActiveDeliveries() int64 {
	if x != nil {
		return x.ActiveDeliveries
	}
	return 0
}

func (x *DeliveryStats) GetCompletedDeliveries() int64 {
	if x != nil {
		return x.CompletedDeliveries
	}
	return 0
}

func (x *DeliveryStats) GetCancelledDeliveries() int64 {
	if x != nil {
		return x.CancelledDeliveries
	}
	return 0
}

func (x *DeliveryStats) GetAverageEtaMinutes() float64 {
	if x != nil {
		return x.AverageEtaMinutes
	}
	return 0
}

func (x *DeliveryStats) GetAverageDistanceKm() float64 {
	if x != nil {
		return x.AverageDistanceKm
	}
	return 0
}

type DeliveryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDirection string                 `protobuf:"bytes,3,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryFilter) Reset() {
	*x = DeliveryFilter{}
	mi := &file_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryFilter) ProtoMessage() {}

func (x *DeliveryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryFilter.ProtoReflect.Descriptor instead.
func (*DeliveryFilter) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryFilter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *DeliveryFilter) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

type AssignDeliveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RestaurantId    string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickupAddress   string                 `protobuf:"bytes,4,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,5,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	RouteDistanceKm float64                `protobuf:"fixed64,6,opt,name=route_distance_km,json=routeDistanceKm,proto3" json:"route_distance_km,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignDeliveryRequest) Reset() {
	*x = AssignDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeliveryRequest) ProtoMessage() {}

func (x *AssignDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeliveryRequest.ProtoReflect.Descriptor instead.
func (*AssignDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *AssignDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssignDeliveryRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *AssignDeliveryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AssignDeliveryRequest) GetPickupAddress() string {
	if x != nil {
		return x.PickupAddress
	}
	return ""
}

func (x *AssignDeliveryRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *AssignDeliveryRequest) GetRouteDistanceKm() float64 {
	if x != nil {
		return x.RouteDistanceKm
	}
	return 0
}

type GetDeliveryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryByIdRequest) Reset() {
	*x = GetDeliveryByIdRequest{}
	mi := &file_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryByIdRequest) ProtoMessage() {}

func (x *GetDeliveryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryByIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeliveryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDeliveryStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDeliveriesByCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Filter        *DeliveryFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveriesByCourierRequest) Reset() {
	*x = GetDeliveriesByCourierRequest{}
	mi := &file_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveriesByCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveriesByCourierRequest) ProtoMessage() {}

func (x *GetDeliveriesByCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveriesByCourierRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveriesByCourierRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeliveriesByCourierRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *GetDeliveriesByCourierRequest) GetFilter() *DeliveryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetDeliveriesByCourierRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetDeliveriesByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveriesByOrderRequest) Reset() {
	*x = GetDeliveriesByOrderRequest{}
	mi := &file_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveriesByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveriesByOrderRequest) ProtoMessage() {}

func (x *GetDeliveriesByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveriesByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveriesByOrderRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *GetDeliveriesByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListAvailableCouriersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   string                 `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableCouriersRequest) Reset() {
	*x = ListAvailableCouriersRequest{}
	mi := &file_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableCouriersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableCouriersRequest) ProtoMessage() {}

func (x *ListAvailableCouriersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableCouriersRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableCouriersRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *ListAvailableCouriersRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *ListAvailableCouriersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetDeliveryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatsRequest) Reset() {
	*x = GetDeliveryStatsRequest{}
	mi := &file_delivery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatsRequest) ProtoMessage() {}

func (x *GetDeliveryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{14}
}

func (x *GetDeliveryStatsRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type CalculateDeliveryETARequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId      string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	RouteDistanceKm float64                `protobuf:"fixed64,2,opt,name=route_distance_km,json=routeDistanceKm,proto3" json:"route_distance_km,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateDeliveryETARequest) Reset() {
	*x = CalculateDeliveryETARequest{}
	mi := &file_delivery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDeliveryETARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDeliveryETARequest) ProtoMessage() {}

func (x *CalculateDeliveryETARequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDeliveryETARequest.ProtoReflect.Descriptor instead.
func (*CalculateDeliveryETARequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{15}
}

func (x *CalculateDeliveryETARequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *CalculateDeliveryETARequest) GetRouteDistanceKm() float64 {
	if x != nil {
		return x.RouteDistanceKm
	}
	return 0
}

func (x *CalculateDeliveryETARequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDeliveryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryHistoryRequest) Reset() {
	*x = GetDeliveryHistoryRequest{}
	mi := &file_delivery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryHistoryRequest) ProtoMessage() {}

func (x *GetDeliveryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeliveryHistoryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type RateCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateCourierRequest) Reset() {
	*x = RateCourierRequest{}
	mi := &file_delivery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateCourierRequest) ProtoMessage() {}

func (x *RateCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateCourierRequest.ProtoReflect.Descriptor instead.
func (*RateCourierRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{17}
}

func (x *RateCourierRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *RateCourierRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RateCourierRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RateCourierRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateCourierRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RegisterCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleType   string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCourierRequest) Reset() {
	*x = RegisterCourierRequest{}
	mi := &file_delivery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCourierRequest) ProtoMessage() {}

func (x *RegisterCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCourierRequest.ProtoReflect.Descriptor instead.
func (*RegisterCourierRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterCourierRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterCourierRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterCourierRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterCourierRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type UpdateCourierAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourierAvailabilityRequest) Reset() {
	*x = UpdateCourierAvailabilityRequest{}
	mi := &file_delivery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourierAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourierAvailabilityRequest) ProtoMessage() {}

func (x *UpdateCourierAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourierAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourierAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCourierAvailabilityRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *UpdateCourierAvailabilityRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type DeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{20}
}

func (x *DeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	Meta          *PageMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset() {
	*x = ListDeliveriesResponse{}
	mi := &file_delivery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesResponse) ProtoMessage() {}

func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{21}
}

func (x *ListDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListDeliveriesResponse) GetMeta() *PageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListCouriersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Couriers      []*Courier             `protobuf:"bytes,1,rep,name=couriers,proto3" json:"couriers,omitempty"`
	Meta          *PageMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouriersResponse) Reset() {
	*x = ListCouriersResponse{}
	mi := &file_delivery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouriersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouriersResponse) ProtoMessage() {}

func (x *ListCouriersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouriersResponse.ProtoReflect.Descriptor instead.
func (*ListCouriersResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{22}
}

func (x *ListCouriersResponse) GetCouriers() []*Courier {
	if x != nil {
		return x.Couriers
	}
	return nil
}

func (x *ListCouriersResponse) GetMeta() *PageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeliveryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *DeliveryStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatsResponse) Reset() {
	*x = DeliveryStatsResponse{}
	mi := &file_delivery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatsResponse) ProtoMessage() {}

func (x *DeliveryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatsResponse.ProtoReflect.Descriptor instead.
func (*DeliveryStatsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{23}
}

func (x *DeliveryStatsResponse) GetStats() *DeliveryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DeliveryETAResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EtaMinutes      int32                  `protobuf:"varint,1,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	RouteDistanceKm float64                `protobuf:"fixed64,2,opt,name=route_distance_km,json=routeDistanceKm,proto3" json:"route_distance_km,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryETAResponse) Reset() {
	*x = DeliveryETAResponse{}
	mi := &file_delivery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryETAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryETAResponse) ProtoMessage() {}

func (x *DeliveryETAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryETAResponse.ProtoReflect.Descriptor instead.
func (*DeliveryETAResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{24}
}

func (x *DeliveryETAResponse) GetEtaMinutes() int32 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

func (x *DeliveryETAResponse) GetRouteDistanceKm() float64 {
	if x != nil {
		return x.RouteDistanceKm
	}
	return 0
}

type DeliveryHistoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	History       []*DeliveryStatusHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryHistoryResponse) Reset() {
	*x = DeliveryHistoryResponse{}
	mi := &file_delivery_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryHistoryResponse) ProtoMessage() {}

func (x *DeliveryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryHistoryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{25}
}

func (x *DeliveryHistoryResponse) GetHistory() []*DeliveryStatusHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type CourierRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *CourierRating         `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierRatingResponse) Reset() {
	*x = CourierRatingResponse{}
	mi := &file_delivery_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRatingResponse) ProtoMessage() {}

func (x *CourierRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRatingResponse.ProtoReflect.Descriptor instead.
func (*CourierRatingResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{26}
}

func (x *CourierRatingResponse) GetRating() *CourierRating {
	if x != nil {
		return x.Rating
	}
	return nil
}

type CourierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courier       *Courier               `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierResponse) Reset() {
	*x = CourierResponse{}
	mi := &file_delivery_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierResponse) ProtoMessage() {}

func (x *CourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierResponse.ProtoReflect.Descriptor instead.
func (*CourierResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{27}
}

func (x *CourierResponse) GetCourier() *Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_delivery_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{28}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_delivery_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{29}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\vdelivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"Q\n" +
	"\bPageMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xe4\x02\n" +
	"\aCourier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12)\n" +
	"\x10total_deliveries\x18\a \x01(\x05R\x0ftotalDeliveries\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xda\x04\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12#\n" +
	"\rrestaurant_id\x18\x04 \x01(\tR\frestaurantId\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epickup_address\x18\a \x01(\tR\rpickupAddress\x12)\n" +
	"\x10delivery_address\x18\b \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15estimated_eta_minutes\x18\t \x01(\x05R\x13estimatedEtaMinutes\x12;\n" +
	"\vpickup_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12A\n" +
	"\x0edelivered_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rdeliveredTime\x12*\n" +
	"\x11route_distance_km\x18\f \x01(\x01R\x0frouteDistanceKm\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc1\x01\n" +
	"\x15DeliveryStatusHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"old_status\x18\x03 \x01(\tR\toldStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tR\tnewStatus\x129\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\xe7\x01\n" +
	"\rCourierRating\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\tR\tcourierId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xad\x02\n" +
	"\rDeliveryStats\x12)\n" +
	"\x10total_deliveries\x18\x01 \x01(\x03R\x0ftotalDeliveries\x12+\n" +
	"\x11active_deliveries\x18\x02 \x01(\x03R\x10activeDeliveries\x121\n" +
	"\x14completed_deliveries\x18\x03 \x01(\x03R\x13completedDeliveries\x121\n" +
	"\x14cancelled_deliveries\x18\x04 \x01(\x03R\x13cancelledDeliveries\x12.\n" +
	"\x13average_eta_minutes\x18\x05 \x01(\x01R\x11averageEtaMinutes\x12.\n" +
	"\x13average_distance_km\x18\x06 \x01(\x01R\x11averageDistanceKm\"h\n" +
	"\x0eDeliveryFilter\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\x03 \x01(\tR\rsortDirection\"\xf6\x01\n" +
	"\x15AssignDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0epickup_address\x18\x04 \x01(\tR\rpickupAddress\x12)\n" +
	"\x10delivery_address\x18\x05 \x01(\tR\x0fdeliveryAddress\x12*\n" +
	"\x11route_distance_km\x18\x06 \x01(\x01R\x0frouteDistanceKm\"(\n" +
	"\x16GetDeliveryByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xac\x01\n" +
	"\x1dGetDeliveriesByCourierRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x123\n" +
	"\x06filter\x18\x02 \x01(\v2\x1b.delivery.v1.DeliveryFilterR\x06filter\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.delivery.v1.PaginationR\n" +
	"pagination\"8\n" +
	"\x1bGetDeliveriesByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"z\n" +
	"\x1cListAvailableCouriersRequest\x12!\n" +
	"\fvehicle_type\x18\x01 \x01(\tR\vvehicleType\x127\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x17.delivery.v1.PaginationR\n" +
	"pagination\"8\n" +
	"\x17GetDeliveryStatsRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\"\x82\x01\n" +
	"\x1bCalculateDeliveryETARequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12*\n" +
	"\x11route_distance_km\x18\x02 \x01(\x01R\x0frouteDistanceKm\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"<\n" +
	"\x19GetDeliveryHistoryRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\"\xa1\x01\n" +
	"\x12RateCourierRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"\x87\x01\n" +
	"\x16RegisterCourierRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\"d\n" +
	" UpdateCourierAvailabilityRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\"E\n" +
	"\x10DeliveryResponse\x121\n" +
	"\bdelivery\x18\x01 \x01(\v2\x15.delivery.v1.DeliveryR\bdelivery\"z\n" +
	"\x16ListDeliveriesResponse\x125\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x15.delivery.v1.DeliveryR\n" +
	"deliveries\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.delivery.v1.PageMetaR\x04meta\"s\n" +
	"\x14ListCouriersResponse\x120\n" +
	"\bcouriers\x18\x01 \x03(\v2\x14.delivery.v1.CourierR\bcouriers\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.delivery.v1.PageMetaR\x04meta\"I\n" +
	"\x15DeliveryStatsResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.delivery.v1.DeliveryStatsR\x05stats\"b\n" +
	"\x13DeliveryETAResponse\x12\x1f\n" +
	"\veta_minutes\x18\x01 \x01(\x05R\n" +
	"etaMinutes\x12*\n" +
	"\x11route_distance_km\x18\x02 \x01(\x01R\x0frouteDistanceKm\"W\n" +
	"\x17DeliveryHistoryResponse\x12<\n" +
	"\ahistory\x18\x01 \x03(\v2\".delivery.v1.DeliveryStatusHistoryR\ahistory\"K\n" +
	"\x15CourierRatingResponse\x122\n" +
	"\x06rating\x18\x01 \x01(\v2\x1a.delivery.v1.CourierRatingR\x06rating\"A\n" +
	"\x0fCourierResponse\x12.\n" +
	"\acourier\x18\x01 \x01(\v2\x14.delivery.v1.CourierR\acourier\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\xe3\t\n" +
	"\x0fDeliveryService\x12S\n" +
	"\x0eAssignDelivery\x12\".delivery.v1.AssignDeliveryRequest\x1a\x1d.delivery.v1.DeliveryResponse\x12U\n" +
	"\x0fGetDeliveryById\x12#.delivery.v1.GetDeliveryByIdRequest\x1a\x1d.delivery.v1.DeliveryResponse\x12_\n" +
	"\x14UpdateDeliveryStatus\x12(.delivery.v1.UpdateDeliveryStatusRequest\x1a\x1d.delivery.v1.DeliveryResponse\x12i\n" +
	"\x16GetDeliveriesByCourier\x12*.delivery.v1.GetDeliveriesByCourierRequest\x1a#.delivery.v1.ListDeliveriesResponse\x12e\n" +
	"\x14GetDeliveriesByOrder\x12(.delivery.v1.GetDeliveriesByOrderRequest\x1a#.delivery.v1.ListDeliveriesResponse\x12e\n" +
	"\x15ListAvailableCouriers\x12).delivery.v1.ListAvailableCouriersRequest\x1a!.delivery.v1.ListCouriersResponse\x12\\\n" +
	"\x10GetDeliveryStats\x12$.delivery.v1.GetDeliveryStatsRequest\x1a\".delivery.v1.DeliveryStatsResponse\x12b\n" +
	"\x14CalculateDeliveryETA\x12(.delivery.v1.CalculateDeliveryETARequest\x1a .delivery.v1.DeliveryETAResponse\x12b\n" +
	"\x12GetDeliveryHistory\x12&.delivery.v1.GetDeliveryHistoryRequest\x1a$.delivery.v1.DeliveryHistoryResponse\x12R\n" +
	"\vRateCourier\x12\x1f.delivery.v1.RateCourierRequest\x1a\".delivery.v1.CourierRatingResponse\x12T\n" +
	"\x0fRegisterCourier\x12#.delivery.v1.RegisterCourierRequest\x1a\x1c.delivery.v1.CourierResponse\x12h\n" +
	"\x19UpdateCourierAvailability\x12-.delivery.v1.UpdateCourierAvailabilityRequest\x1a\x1c.delivery.v1.CourierResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.delivery.v1.HealthCheckRequest\x1a .delivery.v1.HealthCheckResponseBcZagithub.com/aitu/food-delivery/delivery-service/internal/infrastructure/grpc/deliverypb;deliverypbb\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_delivery_proto_goTypes = []any{
	(*Pagination)(nil),                       // 0: delivery.v1.Pagination
	(*PageMeta)(nil),                         // 1: delivery.v1.PageMeta
	(*Courier)(nil),                          // 2: delivery.v1.Courier
	(*Delivery)(nil),                         // 3: delivery.v1.Delivery
	(*DeliveryStatusHistory)(nil),            // 4: delivery.v1.DeliveryStatusHistory
	(*CourierRating)(nil),                    // 5: delivery.v1.CourierRating
	(*DeliveryStats)(nil),                    // 6: delivery.v1.DeliveryStats
	(*DeliveryFilter)(nil),                   // 7: delivery.v1.DeliveryFilter
	(*AssignDeliveryRequest)(nil),            // 8: delivery.v1.AssignDeliveryRequest
	(*GetDeliveryByIdRequest)(nil),           // 9: delivery.v1.GetDeliveryByIdRequest
	(*UpdateDeliveryStatusRequest)(nil),      // 10: delivery.v1.UpdateDeliveryStatusRequest
	(*GetDeliveriesByCourierRequest)(nil),    // 11: delivery.v1.GetDeliveriesByCourierRequest
	(*GetDeliveriesByOrderRequest)(nil),      // 12: delivery.v1.GetDeliveriesByOrderRequest
	(*ListAvailableCouriersRequest)(nil),     // 13: delivery.v1.ListAvailableCouriersRequest
	(*GetDeliveryStatsRequest)(nil),          // 14: delivery.v1.GetDeliveryStatsRequest
	(*CalculateDeliveryETARequest)(nil),      // 15: delivery.v1.CalculateDeliveryETARequest
	(*GetDeliveryHistoryRequest)(nil),        // 16: delivery.v1.GetDeliveryHistoryRequest
	(*RateCourierRequest)(nil),               // 17: delivery.v1.RateCourierRequest
	(*RegisterCourierRequest)(nil),           // 18: delivery.v1.RegisterCourierRequest
	(*UpdateCourierAvailabilityRequest)(nil), // 19: delivery.v1.UpdateCourierAvailabilityRequest
	(*DeliveryResponse)(nil),                 // 20: delivery.v1.DeliveryResponse
	(*ListDeliveriesResponse)(nil),           // 21: delivery.v1.ListDeliveriesResponse
	(*ListCouriersResponse)(nil),             // 22: delivery.v1.ListCouriersResponse
	(*DeliveryStatsResponse)(nil),            // 23: delivery.v1.DeliveryStatsResponse
	(*DeliveryETAResponse)(nil),              // 24: delivery.v1.DeliveryETAResponse
	(*DeliveryHistoryResponse)(nil),          // 25: delivery.v1.DeliveryHistoryResponse
	(*CourierRatingResponse)(nil),            // 26: delivery.v1.CourierRatingResponse
	(*CourierResponse)(nil),                  // 27: delivery.v1.CourierResponse
	(*HealthCheckRequest)(nil),               // 28: delivery.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),              // 29: delivery.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),            // 30: google.protobuf.Timestamp
}
var file_delivery_proto_depIdxs = []int32{
	30, // 0: delivery.v1.Courier.created_at:type_name -> google.protobuf.Timestamp
	30, // 1: delivery.v1.Courier.updated_at:type_name -> google.protobuf.Timestamp
	30, // 2: delivery.v1.Delivery.pickup_time:type_name -> google.protobuf.Timestamp
	30, // 3: delivery.v1.Delivery.delivered_time:type_name -> google.protobuf.Timestamp
	30, // 4: delivery.v1.Delivery.created_at:type_name -> google.protobuf.Timestamp
	30, // 5: delivery.v1.Delivery.updated_at:type_name -> google.protobuf.Timestamp
	30, // 6: delivery.v1.DeliveryStatusHistory.changed_at:type_name -> google.protobuf.Timestamp
	30, // 7: delivery.v1.CourierRating.created_at:type_name -> google.protobuf.Timestamp
	7,  // 8: delivery.v1.GetDeliveriesByCourierRequest.filter:type_name -> delivery.v1.DeliveryFilter
	0,  // 9: delivery.v1.GetDeliveriesByCourierRequest.pagination:type_name -> delivery.v1.Pagination
	0,  // 10: delivery.v1.ListAvailableCouriersRequest.pagination:type_name -> delivery.v1.Pagination
	3,  // 11: delivery.v1.DeliveryResponse.delivery:type_name -> delivery.v1.Delivery
	3,  // 12: delivery.v1.ListDeliveriesResponse.deliveries:type_name -> delivery.v1.Delivery
	1,  // 13: delivery.v1.ListDeliveriesResponse.meta:type_name -> delivery.v1.PageMeta
	2,  // 14: delivery.v1.ListCouriersResponse.couriers:type_name -> delivery.v1.Courier
	1,  // 15: delivery.v1.ListCouriersResponse.meta:type_name -> delivery.v1.PageMeta
	6,  // 16: delivery.v1.DeliveryStatsResponse.stats:type_name -> delivery.v1.DeliveryStats
	4,  // 17: delivery.v1.DeliveryHistoryResponse.history:type_name -> delivery.v1.DeliveryStatusHistory
	5,  // 18: delivery.v1.CourierRatingResponse.rating:type_name -> delivery.v1.CourierRating
	2,  // 19: delivery.v1.CourierResponse.courier:type_name -> delivery.v1.Courier
	8,  // 20: delivery.v1.DeliveryService.AssignDelivery:input_type -> delivery.v1.AssignDeliveryRequest
	9,  // 21: delivery.v1.DeliveryService.GetDeliveryById:input_type -> delivery.v1.GetDeliveryByIdRequest
	10, // 22: delivery.v1.DeliveryService.UpdateDeliveryStatus:input_type -> delivery.v1.UpdateDeliveryStatusRequest
	11, // 23: delivery.v1.DeliveryService.GetDeliveriesByCourier:input_type -> delivery.v1.GetDeliveriesByCourierRequest
	12, // 24: delivery.v1.DeliveryService.GetDeliveriesByOrder:input_type -> delivery.v1.GetDeliveriesByOrderRequest
	13, // 25: delivery.v1.DeliveryService.ListAvailableCouriers:input_type -> delivery.v1.ListAvailableCouriersRequest
	14, // 26: delivery.v1.DeliveryService.GetDeliveryStats:input_type -> delivery.v1.GetDeliveryStatsRequest
	15, // 27: delivery.v1.DeliveryService.CalculateDeliveryETA:input_type -> delivery.v1.CalculateDeliveryETARequest
	16, // 28: delivery.v1.DeliveryService.GetDeliveryHistory:input_type -> delivery.v1.GetDeliveryHistoryRequest
	17, // 29: delivery.v1.DeliveryService.RateCourier:input_type -> delivery.v1.RateCourierRequest
	18, // 30: delivery.v1.DeliveryService.RegisterCourier:input_type -> delivery.v1.RegisterCourierRequest
	19, // 31: delivery.v1.DeliveryService.UpdateCourierAvailability:input_type -> delivery.v1.UpdateCourierAvailabilityRequest
	28, // 32: delivery.v1.DeliveryService.HealthCheck:input_type -> delivery.v1.HealthCheckRequest
	20, // 33: delivery.v1.DeliveryService.AssignDelivery:output_type -> delivery.v1.DeliveryResponse
	20, // 34: delivery.v1.DeliveryService.GetDeliveryById:output_type -> delivery.v1.DeliveryResponse
	20, // 35: delivery.v1.DeliveryService.UpdateDeliveryStatus:output_type -> delivery.v1.DeliveryResponse
	21, // 36: delivery.v1.DeliveryService.GetDeliveriesByCourier:output_type -> delivery.v1.ListDeliveriesResponse
	21, // 37: delivery.v1.DeliveryService.GetDeliveriesByOrder:output_type -> delivery.v1.ListDeliveriesResponse
	22, // 38: delivery.v1.DeliveryService.ListAvailableCouriers:output_type -> delivery.v1.ListCouriersResponse
	23, // 39: delivery.v1.DeliveryService.GetDeliveryStats:output_type -> delivery.v1.DeliveryStatsResponse
	24, // 40: delivery.v1.DeliveryService.CalculateDeliveryETA:output_type -> delivery.v1.DeliveryETAResponse
	25, // 41: delivery.v1.DeliveryService.GetDeliveryHistory:output_type -> delivery.v1.DeliveryHistoryResponse
	26, // 42: delivery.v1.DeliveryService.RateCourier:output_type -> delivery.v1.CourierRatingResponse
	27, // 43: delivery.v1.DeliveryService.RegisterCourier:output_type -> delivery.v1.CourierResponse
	27, // 44: delivery.v1.DeliveryService.UpdateCourierAvailability:output_type -> delivery.v1.CourierResponse
	29, // 45: delivery.v1.DeliveryService.HealthCheck:output_type -> delivery.v1.HealthCheckResponse
	33, // [33:46] is the sub-list for method output_type
	20, // [20:33] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
