services:

  postgres:
    image: postgres:15
    container_name: user-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: userdb

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/001_init.sql:ro

  redis:
    image: redis:7
    container_name: user-redis

    ports:
      - "6380:6379"

  nats:
    image: nats:latest
    container_name: user-nats

    ports:
      - "4223:4222"

  user-service:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile

    container_name: user-service

    ports:
      - "50052:50052"

    depends_on:
      - postgres
      - redis
      - nats

    env_file:
      - ../../.env

volumes:
  postgres_data: